import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/widgets/header/header";
import { NextIntlClientProvider } from "next-intl";
import { Container } from "@/shared/components/ui/container";

const jetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth dark">
      <body className={`${jetBrainsMono.variable}  antialiased`}>
        <NextIntlClientProvider>
          <Container>
            <Header />
          </Container>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
